"""Initial migration after refactoring

Revision ID: 0aec5bb098ee
Revises: 
Create Date: 2025-06-20 12:53:14.827718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aec5bb098ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_price_adders',
    sa.Column('ip_adder', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('drip_tray_adder', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('company_name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_company_name'), ['company_name'], unique=True)

    op.create_table('discount_rules',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=True),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discount_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discount_rules_component_type'), ['component_type'], unique=False)

    op.create_table('inertia_bases',
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inertia_bases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inertia_bases_part_number'), ['part_number'], unique=True)

    op.create_table('price_lists',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pumps',
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('series', sa.Enum('NBG', 'CR', 'TP', 'CM', 'MAGNA', 'UPS', 'CRE', 'TPE', 'NK', name='pumpseries'), nullable=False),
    sa.Column('frame_size', sa.String(length=50), nullable=True),
    sa.Column('poles', sa.Integer(), nullable=True),
    sa.Column('power_kw', sa.Float(), nullable=True),
    sa.Column('flow_rate', sa.Float(), nullable=True),
    sa.Column('head', sa.Float(), nullable=True),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pumps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pumps_part_number'), ['part_number'], unique=True)

    op.create_table('rubber_mounts',
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('mount_type', sa.String(length=100), nullable=True),
    sa.Column('load_capacity_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rubber_mounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rubber_mounts_part_number'), ['part_number'], unique=True)

    op.create_table('seismic_springs',
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('spring_rate_k', sa.Float(), nullable=True),
    sa.Column('max_deflection_mm', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seismic_springs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seismic_springs_part_number'), ['part_number'], unique=True)

    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'SALES', 'MANAGER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contacts',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=True)

    op.create_table('deals',
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.Enum('NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'NT', 'ACT', name='australianstate'), nullable=False),
    sa.Column('deal_type', sa.Enum('HVAC', 'HYDRAULIC', 'HYDRONIC', 'DATA_CENTRES', 'MERCHANT', 'WHOLESALER', 'OEM', name='dealtype'), nullable=False),
    sa.Column('stage', sa.Enum('SALES_LEAD', 'TENDER', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST', 'ABANDONED', name='dealstage'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_list_items',
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('component_part_number', sa.String(length=100), nullable=False),
    sa.Column('list_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_list_items_component_part_number'), ['component_part_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_list_items_component_type'), ['component_type'], unique=False)

    op.create_table('pump_assemblies',
    sa.Column('assembly_number', sa.String(length=50), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.Column('inertia_base_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inertia_base_id'], ['inertia_bases.id'], ),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pump_assemblies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pump_assemblies_assembly_number'), ['assembly_number'], unique=True)

    op.create_table('pump_ip_ratings',
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pumps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assembly_springs',
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.Column('spring_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['pump_assemblies.id'], ),
    sa.ForeignKeyConstraint(['spring_id'], ['seismic_springs.id'], ),
    sa.PrimaryKeyConstraint('assembly_id', 'spring_id', 'id')
    )
    op.create_table('deal_contacts',
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('deal_id', 'contact_id')
    )
    op.create_table('quotes',
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number')
    )
    op.create_table('quote_line_items',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_line_items')
    op.drop_table('quotes')
    op.drop_table('deal_contacts')
    op.drop_table('assembly_springs')
    op.drop_table('pump_ip_ratings')
    with op.batch_alter_table('pump_assemblies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pump_assemblies_assembly_number'))

    op.drop_table('pump_assemblies')
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_list_items_component_type'))
        batch_op.drop_index(batch_op.f('ix_price_list_items_component_part_number'))

    op.drop_table('price_list_items')
    op.drop_table('deals')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_contacts_company_id'))

    op.drop_table('contacts')
    op.drop_table('users')
    with op.batch_alter_table('seismic_springs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seismic_springs_part_number'))

    op.drop_table('seismic_springs')
    with op.batch_alter_table('rubber_mounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rubber_mounts_part_number'))

    op.drop_table('rubber_mounts')
    with op.batch_alter_table('pumps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pumps_part_number'))

    op.drop_table('pumps')
    op.drop_table('price_lists')
    with op.batch_alter_table('inertia_bases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inertia_bases_part_number'))

    op.drop_table('inertia_bases')
    with op.batch_alter_table('discount_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discount_rules_component_type'))

    op.drop_table('discount_rules')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_company_name'))

    op.drop_table('companies')
    op.drop_table('additional_price_adders')
    # ### end Alembic commands ###
