"""Update DealType enum with new values

Revision ID: 0cf8002268a3
Revises: ef99f237ce53
Create Date: 2025-07-02 15:45:32.227080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf8002268a3'
down_revision = 'ef99f237ce53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- NEW: Manually update old data BEFORE changing the column type ---
    # This is crucial. We clean up the old values first.
    op.execute("UPDATE deals SET deal_type = 'PLUMBING' WHERE deal_type = 'HYDRAULIC'")
    op.execute("UPDATE deals SET deal_type = 'HYDRONIC_HEATING' WHERE deal_type = 'HYDRONIC'")
    # --- END NEW SECTION ---

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.alter_column('deal_type',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('HVAC', 'PLUMBING', 'HYDRONIC_HEATING', 'DATA_CENTRES', 'MERCHANT', 'WHOLESALER', 'OEM', name='dealtype'),
               existing_nullable=False)

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- NEW: Manually revert the data changes on downgrade ---
    op.execute("UPDATE deals SET deal_type = 'HYDRAULIC' WHERE deal_type = 'PLUMBING'")
    op.execute("UPDATE deals SET deal_type = 'HYDRONIC' WHERE deal_type = 'HYDRONIC_HEATING'")
    # --- END NEW SECTION ---

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.alter_column('deal_type',
               existing_type=sa.Enum('HVAC', 'PLUMBING', 'HYDRONIC_HEATING', 'DATA_CENTRES', 'MERCHANT', 'WHOLESALER', 'OEM', name='dealtype'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###